### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by AllanWang** [sidharthkuruvila/ocaml-ide#1] opened 2017-09-25 16:10 UTC
How exactly do you build this plugin? Have you considered automating that with Travis as well? I'd like to get a formatter running for OCaml and I'd like to contribute this once I know how to build it.

**Comment by sidharthkuruvila** [comment] 2017-09-25 17:12
Run the following commands

    ./gradlew generateOcamlLexer
    ./gradlew generateOcamlPsiAndParser
    ./gradlew buildPlugin

The plugin will be located at build/distributions/ocaml-idea-0.0.1-SNAPSHOT.zip

I couldn't get it to install on Idea Ultimate, but it did work on the Idea community edition when I last tried it.

Will test on community tomorrow and update the README.md file and the travis build if that works.

**Comment by AllanWang** [comment] 2017-09-25 17:58
Thanks. I will test it on ultimate and try adding automatic Travis builds

**Comment by sidharthkuruvila** [comment] 2017-09-28 18:08
After some research, it appears that the the allowed idea versions entry is getting updated when the plugin is built.

This is what I want

     <idea-version since-build="145"/>

But this is what I find in the plugin.xml

    <idea-version since-build="171.3780.107" until-build="171.9999"/>

I'm looking into why this might be.

**Comment by sidharthkuruvila** [comment] 2017-09-28 20:28
Ok the issue is that the gradle plugin overrides the build idea version. To prevent this I needed to add a `intellij.updateSinceUntilBuild false`.

You should be able to build and install the plugin now.

**Comment by AllanWang** [comment] 2017-09-28 20:37
Awesome. I will check it out in a bit. Have you considered adding a script to have Travis compile it and upload a release with each master update?

**Comment by sidharthkuruvila** [comment] 2017-09-28 20:43
Github has a notion of release artifacts, but that requires the use of tags for each release. I'll need to look into this a bit.

**Comment by AllanWang** [comment] 2017-09-28 20:44
You can auto generate tags per release based on the travis build number. But if your intent is not to clutter your releases, you may also have it upload to a different repo.

**Comment by sidharthkuruvila** [comment] 2017-09-28 20:54
Hmm let me look at the options. It might make sense to have explicitly tagged releases. I currently don't anything in the way of quality gating for releases. And I have had a bunch of broken commits in the past.

**Comment by AllanWang** [comment] 2017-09-29 01:47
I did a basic test by building it and installing it in IntelliJ Ultimate 2017.2.4

With a basic test:

```OCaml
let test ab =
ab *. 2.0
```

Formatting the file resulted in:

```java
null
java.lang.NullPointerException
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:876)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2324)
	at org.ocaml.merlin.Merlin.makeRequest(Merlin.kt:102)
	at org.ocaml.merlin.Merlin.tellSource(Merlin.kt:45)
	at org.ocaml.ide.components.impl.MerlinServiceComponentImpl.reloadFileIfModified(MerlinServiceComponentImpl.kt:52)
	at org.ocaml.ide.components.impl.MerlinServiceComponentImpl.errors(MerlinServiceComponentImpl.kt:32)
	at org.ocaml.ide.highlighter.MerlinErrorHighlightingAnnotator.doAnnotate(MerlinErrorHighlightingAnnotator.kt:36)
	at org.ocaml.ide.highlighter.MerlinErrorHighlightingAnnotator.doAnnotate(MerlinErrorHighlightingAnnotator.kt:17)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sidharthkuruvila** [comment] 2017-09-29 01:56
Can you create a new issue for this? I plan on closing this issue when I add the released version for download.

**Comment by AllanWang** [comment] 2017-09-29 01:57
Done: #2

**Closed as completed** 2017-11-25 04:01 UTC
